---
# tasks file for agent
- name: creates directorys
  ansible.builtin.file:
    path: "{{item}}"     
    state: directory
  loop:
    - /opt/gitlab
    - /opt/gitlab/config
    - /opt/gitlab/logs
    - /opt/gitlab/data
    - /opt/gitlab-runner
    - /opt/gitlab-runner/

- name: copy docker-compose.yml
  copy:
    src: ./roles/agent/files/docker-compose.yml
    dest: /home/ubuntu/

- name: replace ip runner
  ansible.builtin.replace:
    path: /home/ubuntu/docker-compose.yml
    regexp: "185.185.185.185"
    replace: "{{ansible_ssh_host}}"

- name: start docker-compose
  shell: docker-compose up -d