global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 30s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: node-exporter
    scrape_interval: 30s
    static_configs:
    - targets: ["monitoring.warspoon.ru:9100", "server1.warspoon.ru:9100", "ci.warspoon.ru:9100"]

  - job_name: application
    scrape_interval: 30s
    static_configs:
    - targets: ["warspoon.ru:8080"]

rule_files:
  - prometheus_alerts_rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - monitoring.warspoon.ru:9093