---
# tasks file for nginx
- name: Install Nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Remove default nginx config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
    
- name: Copy configuration
  copy:
    src: ./roles/nginx/files/default
    dest: /etc/nginx/sites-available

- name: Start nginx
  systemd:
    name: nginx
    state: started
    enabled: yes