---
- hosts: servers
  remote_user: ubuntu

  roles:
    - role: docker
#    - role: nginx
    - role: target
      
- hosts: prod_servers
  remote_user: ubuntu

  roles:
    - role: docker
    - role: target

- hosts: runners
  become: yes

  roles:
    - role: docker
    - role: agent
    - role: target

- hosts: monitoring
  remote_user: ubuntu

  roles:
    - role: docker  
    - role: observe
    - role: target
    - role: loki